apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hub
manifests:
  rawYaml:
    - ./k8s/*
build:
  artifacts:
    - image: holaplex/hub
      docker:
        target: development
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/**/**/**/**/*.tsx'
            dest: .
          - src: 'src/**/**/**/**/**/*.css'
            dest: .
          - src: 'src/**/**/**/**/**/*.ts'
            dest: .
          - src: 'src/queries/*.graphql'
            dest: .

portForward:
  - resourceType: service
    resourceName: apisix-gateway
    namespace: ingress-apisix
    port: 80
    localPort: 9080

deploy:
  helm:
    releases:
      - name: redpanda
        repo: https://charts.redpanda.com/
        remoteChart: redpanda
        valuesFiles:
          - values.redpanda.yaml
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        valuesFiles:
          - values.mailhog.yaml
      - name: kratos-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.kratos.postgresql.yaml
      - name: kratos
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: kratos
        valuesFiles:
          - values.kratos.yaml
      - name: hub-identities
        remoteChart: hub-identities
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.identities.yaml
      - name: hub-orgs-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.orgs.postgresql.yaml
      - name: svix
        remoteChart: svix
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.svix.yaml
      - name: svix-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.svix.postgresql.yaml
      - name: svix-redis
        repo: https://charts.bitnami.com/bitnami
        remoteChart: redis
        setValues:
          architecture: standalone
      - name: hub-orgs
        remoteChart: hub-orgs
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.orgs.yaml
      - name: hub-gateway
        createNamespace: true
        namespace: ingress-apisix
        remoteChart: hub-gateway
        repo: https://charts.holaplex.com
        #chartPath: ./../helm-charts/charts/hub-gateway
        valuesFiles:
          - values.gateway.yaml
          - secrets.gateway.yaml
