apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hub
manifests:
  rawYaml:
    - ./k8s/*
  kustomize:
    paths:
      - ../hub-gateway
build:
  artifacts:
  - image: holaplex/hub
    docker:
      target: development
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/**/**/**/**/*.tsx'
        dest: .
      - src: 'src/**/**/**/**/**/*.css'
        dest: .
      - src: 'src/**/**/**/**/**/*.ts'
        dest: .
      - src: 'src/queries/*.graphql'
        dest: .

portForward:
- resourceType: service
  resourceName: apisix-gateway
  namespace: ingress-apisix
  port: 80
  localPort: 9080

deploy:
  helm:
    releases:
      - name: redpanda
        repo: https://charts.redpanda.com/
        remoteChart: redpanda
        valuesFiles:
          - values.redpanda.yaml
      - name: apisix
        repo: https://apache.github.io/apisix-helm-chart
        namespace: ingress-apisix
        remoteChart: apisix
        valuesFiles:
          - values.apisix.yaml
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        valuesFiles:
          - values.mailhog.yaml
      - name: kratos-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
        - values.kratos.postgresql.yaml
      - name: kratos
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: kratos
        valuesFiles:
          - values.kratos.yaml
      - name: hub-identities
        remoteChart: hub-identities
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.identities.yaml
      - name: hub-orgs-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.orgs.postgresql.yaml
      - name: hub-orgs
        remoteChart: hub-orgs
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.orgs.yaml
      - name: federated-router
        remoteChart: oci://ghcr.io/apollographql/helm-charts/router
        valuesFiles:
          - values.router.yaml
          - secrets.router.yaml
