apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hub
manifests:
  rawYaml:
    - ./k8s/*
build:
  artifacts:
    - image: holaplex/hub
      docker:
        target: development
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/queries/*.graphql'
            dest: .
          - src: 'src/mutations/*.graphql'
            dest: .

portForward:
  - resourceType: service
    resourceName: apisix-gateway
    namespace: ingress-apisix
    port: 80
    localPort: 9080
  - resourceType: service
    resourceName: federated-router
    namespace: default
    port: 80
    localPort: 3005

deploy:
  helm:
    releases:
      - name: hub-gateway
        createNamespace: true
        namespace: ingress-apisix
        remoteChart: hub-gateway
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.gateway.yaml
          - secrets.gateway.yaml
      - name: redpanda
        repo: https://charts.redpanda.com/
        remoteChart: redpanda
        valuesFiles:
          - values.redpanda.yaml
      - name: svix-redis
        repo: https://charts.bitnami.com/bitnami
        remoteChart: redis
        setValues:
          architecture: standalone
          auth:
            enabled: false
      - name: kratos-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.kratos.postgresql.yaml
      - name: hub-customers-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.customers.postgresql.yaml
      - name: hydra-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.hydra.postgresql.yaml
      - name: keto-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.keto.postgresql.yaml
      - name: svix-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.svix.postgresql.yaml
      - name: hub-orgs-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.orgs.postgresql.yaml
      - name: hub-treasuries-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - values.treasuries.postgresql.yaml
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        valuesFiles:
          - values.mailhog.yaml
      - name: kratos
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: kratos
        valuesFiles:
          - values.kratos.yaml
      - name: keto
        remoteChart: hub-permissions
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.keto.yaml
      - name: hydra
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: hydra
        valuesFiles:
          - values.hydra.yaml
      - name: hub-identities
        remoteChart: hub-identities
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.identities.yaml
          - secrets.identities.yaml
      - name: svix
        remoteChart: svix
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.svix.yaml
          - secrets.svix.yaml
      - name: hub-orgs
        remoteChart: hub-orgs
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.orgs.yaml
          - secrets.orgs.yaml
      - name: hub-customers
        remoteChart: hub-customers
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.customers.yaml
          - secrets.customers.yaml
      - name: hub-credentials
        remoteChart: hub-credentials
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.credentials.yaml
          - secrets.credentials.yaml
      - name: federated-router
        remoteChart: oci://ghcr.io/apollographql/helm-charts/router
        valuesFiles:
          - values.router.yaml
          - secrets.router.yaml
      - name: hub-treasuries
        remoteChart: hub-treasuries
        repo: https://charts.holaplex.com
        valuesFiles:
          - values.treasuries.yaml
          - secrets.treasuries.yaml
