apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hub
build:
  artifacts:
    - image: hub-ui
      docker:
        target: development
        dockerfile: Dockerfile
        buildArgs:
          APP_FQDN: http://hub.127.0.0.1.nip.io:9080
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/queries/*.graphql'
            dest: .
          - src: 'src/mutations/*.graphql'
            dest: .

portForward:
  - resourceType: service
    resourceName: apisix-gateway
    namespace: ingress-apisix
    port: 80
    localPort: 9080
  - resourceType: service
    resourceName: federated-router
    namespace: default
    port: 80
    localPort: 3005
deploy:
  helm:
    releases:
      - name: hub-gateway
        createNamespace: true
        namespace: ingress-apisix
        remoteChart: hub-gateway
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.gateway.yaml
      - name: hub-permissions
        remoteChart: hub-permissions
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.permissions.yaml
          - .helm/secrets.permissions.yaml
      - name: redpanda
        repo: https://charts.redpanda.com/
        remoteChart: redpanda
        valuesFiles:
          - .helm/values.redpanda.yaml
      - name: hub-ui
        repo: https://charts.holaplex.com
        remoteChart: hub-ui
        setValueTemplates:
          fullnameOverride: hub-ui
          image.repository: '{{ .IMAGE_REPO_hub_ui }}'
          image.tag: '{{ .IMAGE_TAG_hub_ui }}'
        valuesFiles:
          - .helm/secrets.ui.yaml
      - name: kratos-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.kratos.postgresql.yaml
      - name: hub-customers-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.customers.postgresql.yaml
      - name: hub-credits-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.credits.postgresql.yaml
      - name: hub-nfts-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.nfts.postgresql.yaml
      - name: hub-nfts-solana-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.nfts-solana.postgresql.yaml
      - name: hydra-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.hydra.postgresql.yaml
      - name: keto-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.keto.postgresql.yaml
      - name: svix-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.svix.postgresql.yaml
      - name: hub-orgs-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.orgs.postgresql.yaml
      - name: hub-webhooks-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.webhooks.postgresql.yaml
      - name: hub-treasuries-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.treasuries.postgresql.yaml
      - name: hub-analytics-db
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        valuesFiles:
          - .helm/values.analytics.postgresql.yaml
      - name: mailhog
        repo: https://codecentric.github.io/helm-charts
        remoteChart: mailhog
        valuesFiles:
          - .helm/values.mailhog.yaml
      - name: kratos
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: kratos
        valuesFiles:
          - .helm/values.kratos.yaml
      - name: hydra
        repo: https://k8s.ory.sh/helm/charts
        remoteChart: hydra
        valuesFiles:
          - .helm/values.hydra.yaml
      - name: hub-credits
        remoteChart: hub-credits
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.credits.yaml
          - .helm/secrets.credits.yaml
      - name: hub-identities
        remoteChart: hub-identities
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.identities.yaml
          - .helm/secrets.identities.yaml
      - name: hub-analytics
        remoteChart: hub-analytics
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.analytics.yaml
          - .helm/secrets.analytics.yaml
      - name: hub-orgs
        remoteChart: hub-orgs
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.orgs.yaml
          - .helm/secrets.orgs.yaml
      - name: hub-webhooks
        remoteChart: hub-webhooks
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.webhooks.yaml
          - .helm/secrets.webhooks.yaml
      - name: hub-nfts-solana
        remoteChart: hub-nfts-solana
        repo: https://charts.holaplex.com
        version: 0.4.1
        valuesFiles:
          - .helm/values.nfts-solana.yaml
          - .helm/secrets.nfts-solana.yaml
      - name: hub-nfts
        remoteChart: hub-nfts
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.nfts.yaml
          - .helm/secrets.nfts.yaml
      - name: hub-customers
        remoteChart: hub-customers
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.customers.yaml
          - .helm/secrets.customers.yaml
      - name: hub-credentials
        remoteChart: hub-credentials
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.credentials.yaml
          - .helm/secrets.credentials.yaml
      - name: federated-router
        remoteChart: oci://ghcr.io/apollographql/helm-charts/router
        version: 1.19.0
        valuesFiles:
          - .helm/values.router.yaml
          - .helm/secrets.router.yaml
      - name: hub-treasuries
        remoteChart: hub-treasuries
        repo: https://charts.holaplex.com
        valuesFiles:
          - .helm/values.treasuries.yaml
          - .helm/secrets.treasuries.yaml
