managedFederation:
  graphRef: hub-dev@current

router:
  configuration:
    include_subgraph_errors:
      all: true
    supergraph:
      introspection: true
    headers:
      all:
        request:
          - propagate:
              matching: .*