image:
  pullPolicy: Always

migrate:
  image:
    pullPolicy: Always

environment:
  port: '80'
  oryBaseUrl: http://hydra-admin
  kafkaBrokers: 'redpanda-0.redpanda.default.svc.cluster.local.:9093'
  svixBaseUrl: "http://svix.default.svc:80"
