image:
  pullPolicy: Always

migrate:
  image:
    pullPolicy: Always

environment:
  port: '80'
  oryBaseUrl: http://hydra-admin
  kafkaBrokers: "hub-eventbus-cluster-0.hub-eventbus-cluster.default.svc.cluster.local:9093"
  svixBaseUrl: "http://svix.default.svc:80"
