image:
  pullPolicy: Always

migrate:
  image:
    pullPolicy: Always

environment:
  port: '80'
  kafkaUsername: admin
  kafkaSsl: false
  kafkaBrokers: 'hub-eventbus-cluster-0.hub-eventbus-cluster.default.svc.cluster.local:9093'
<<<<<<< HEAD
  solanaKeyPairPath: '/app/keypair.json'
=======
  solanaKeyPairPath: "/app/keypair.json"
>>>>>>> 422a050 (feat: view drops)
