image:
  repository: mpwsh/svix-server
  pullPolicy: IfNotPresent
  tag: "latest"

secrets:
  enabled: true
  entries:
    jwtSecret: "supersecret"
    dsn: "postgresql://svix:svix@svix-db-postgresql:5432/svix"

environment:
  logLevel: "info"
  queueType: "memory"
  waitForServices: true
  redisDsn: "redis://svix-redis-master:6379"
