hubNamespace: default
routes:
- name: api
  serviceName: federated-router
  servicePort: 80
  subdomain: api
  paths:
    - /graphql
  methods:
    - GET
    - POST
  require_auth: true
  regex_uri: ["/graphql", "/"]
  #policy: "hub/graphql/example"
  #schema_query: "{ _service { sdl } }"

- name: ui-public
  subdomain: hub
  serviceName: hub
  servicePort: 80
  methods:
    - GET
    - POST
  paths:
    - /
    - /registration
    - /verification
    - /login
    - /recovery
    - /holaplex.svg
    - /_next/static/*
    - /__nextjs_original-stack-frame
    - /api/.ory/*

- name: ui-private
  subdomain: hub
  serviceName: hub
  servicePort: 80
  require_auth: true
  methods:
    - GET
  paths:
    - /organizations
