hubNamespace: default
routes:
- name: api
  serviceName: hub-orgs
  servicePort: 80
  subdomain: 'api'
  paths:
    - /organization
    - /projects
    - /credentials
    - /webhooks/*
  methods:
    - GET
    - POST
    - DELETE
  require_auth: true
  regex_uri: [ "^/(.*)", "/v1/$1" ]
  policy: "hub/api/orgs"

- name: login-callback
  serviceName: hub-orgs
  servicePort: 80
  subdomain: 'hub'
  paths:
    - /login/callback
  methods:
    - GET
    - POST
  require_auth: true

- name: ui-public
  subdomain: hub
  serviceName: hub
  servicePort: 80
  methods:
    - GET
    - POST
  paths:
    - /
    - /registration
    - /verification
    - /login
    - /recovery
    - /holaplex.svg
    - /_next/static/*
    - /__nextjs_original-stack-frame
    - /api/.ory/*
