managedFederation:
  graphRef: hub-dev@current

extraEnvVars:
  - name: APOLLO_ROUTER_LOG
    value: debug

router:
  configuration:
    include_subgraph_errors:
      all: true
    supergraph:
      introspection: true
    headers:
      all:
        request:
          - propagate:
              matching: .*