hubNamespace: default
domain: 127.0.0.1.nip.io
port: 9080
sessionCookieName: "hub_session"

routes:
- name: api
  serviceName: hub-orgs
  servicePort: 80
  subdomain: api
  paths:
    - /v1/organization
    - /v1/organizations
    - /v1/projects
    - /v1/projects/*
    - /v1/affiliations
    - /v1/members
    - /v1/credentials
    - /v1/credentials/*
    - /v1/webhook/events
    - /v1/webhooks/*
    - /v1/members
    - /v1/members/*
    - /v1/invites
    - /v1/invites/*
  methods:
    - GET
    - POST
    - DELETE
  require_auth: true
  require_org: true
  policy: "hub/api/orgs"

- name: hub-browser-api
  serviceName: hub-orgs
  servicePort: 80
  subdomain: hub
  paths:
    - /browser/login
    - /browser/organizations/*
  methods:
    - POST
  require_auth: true

- name: ui-private
  subdomain: hub
  serviceName: hub
  servicePort: 80
  require_auth: true
  require_org: true
  methods:
    - GET
  paths:
    - /organization/*
    - /projects/*

- name: ui-public
  subdomain: hub
  serviceName: hub
  servicePort: 80
  methods:
    - GET
    - POST
  paths:
    - /
    - /registration
    - /verification
    - /login
    - /recovery
    - /holaplex.svg
    - /_next/static/*
    - /__nextjs_original-stack-frame
    - /api/.ory/*
