ingress:
  enabled: true
  ingressClassName: apisix
  annotations:
    k8s.apisix.apache.org/enable-websocket: "true"
  hosts:
    - host: mail.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix

auth:
  enabled: true
  #user/pw: test/test
  fileContents: "test:$2a$04$qxRo.ftFoNep7ld/5jfKtuBTnGqff/fZVyj53mUC5sVf9dtDLAi/S"

