apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-ui
spec:
  selector:
    matchLabels:
      app: hub-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: hub-ui
    spec:
      containers:
        - name: hub
          image: holaplex/hub
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_GRAPHQL_ENDPOINT
              value: http://hub.127.0.0.1.nip.io:9080/graphql
            - name: GRAPHQL_ENDPOINT
              value: http://apisix-gateway-internal.ingress-apisix.svc.cluster.local/graphql
            - name: KRATOS_ENDPOINT
              value: http://kratos-public
            - name: NEXT_PUBLIC_APP_FQDN
              value: http://hub.127.0.0.1.nip.io:9080
            - name: KRATOS_ENDPOINT
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGJjMmIzQjM1NTJDMWZGZTg5MTAzMjZjRTI0MzllRkFBQ2NFM2UxMWIiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY3NzU5MzM5ODM3NiwibmFtZSI6Imh1YnRlc3QifQ.a_o3-pp_ua6ReyoARCWpGJTRrynFGYpZ1LyURNTF2f0
