apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hub-ui
  labels:
    kubernetes.io/service-name: hub-ui
addressType: FQDN
ports:
  - name: '' 
    appProtocol: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - host.docker.internal