import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { Session, Identity } from '@ory/client';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { AxiosError } from 'axios';
import Link from 'next/link';
import ory from '../modules/ory/sdk';
import { LogoutLink } from '../modules/ory';

const inter = Inter({ subsets: ['latin'] });

// Returns either the email or the username depending on the user's Identity Schema
const getUserName = (identity: Identity) => identity.traits.email || identity.traits.username;

export default function Home() {
  const router = useRouter();

  const [session, setSession] = useState<Session | undefined>();
  // const [logoutUrl, setLogoutUrl] = useState<string | undefined>();
  const onLogout = LogoutLink();

  useEffect(() => {
    ory
      .toSession()
      .then(({ data }) => {
        // User has a session!
        setSession(data);
        // Create a logout url
        // ory.createBrowserLogoutFlow().then(({ data }) => {
        //   setLogoutUrl(data.logout_url);
        // });
      })
      .catch((err: AxiosError) => {
        // Redirect to ory inbuilt login page
        //return router.push(edgeConfig.basePath + '/ui/login');

        switch (err.response?.status) {
          case 403:
          // This is a legacy error code thrown. See code 422 for
          // more details.
          case 422:
            // This status code is returned when we are trying to
            // validate a session which has not yet completed
            // its second factor
            return router.push('/login?aal=aal2');
          case 401:
            // the user is not logged in
            return router.push('/login');
          // do nothing,
          //return;
        }

        // Something else happened!
        return Promise.reject(err);
      });
  }, [router]);

  if (!session) {
    // Still loading
    return null;
  }

  return (
    <>
      <Head>
        <title>Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {session && <>Welcome {getUserName(session?.identity)}!</>}
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <div className="text-2xl">HUB</div>
          </div>
        </div>
        <p className={styles.description}>
          <button onClick={onLogout}>Log out</button>
        </p>
      </main>
    </>
  );
}
