fullnameOverride: 'hub-eventbus-cluster'
statefulset:
  replicas: 1
post_install_job:
  enabled: false
post_upgrade_job:
  enabled: false
console:
  enabled: false
tls:
  enabled: false
auth:
  sasl:
    enabled: true
    users:
      - name: admin
        password: change-me
        mechanism: SCRAM-SHA-512
