image:
  pullPolicy: Always

migrate:
  image:
    pullPolicy: Always

environment:
  oryBaseUrl: http://hydra-admin
  kafkaUsername: admin
  kafkaSsl: false
  kafkaBrokers: 'hub-eventbus-cluster-0.hub-eventbus-cluster.default.svc.cluster.local:9093'
