name: Release Image
on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - '.helm/*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SERVICE_NAME: frontend
  CACHE_CONFIG: type=s3,region=${{ vars.AWS_REGION }},bucket=${{ vars.AWS_BUCKET }},access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }},secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_ORG }}/hub-ui

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ${{ matrix.arch }}
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker context create ci
          docker context use ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
          version: v0.10.4
          endpoint: ci
      - name: Setup variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "::set-output name=fqdn::https://hub.holaplex.com"
          else
            echo "::set-output name=fqdn::https://hub.holaplex.dev"
          fi

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push hub-ui
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            APP_FQDN=${{ steps.vars.outputs.fqdn }}
          push: true
          provenance: false
          platforms: linux/${{ matrix.arch }}
          tags: ${{ env.DOCKERHUB_REPO }}:latest-${{ matrix.arch }}
          cache-from: ${{ env.CACHE_CONFIG }},prefix=buildx/hub-ui/${{ matrix.arch }}/
          cache-to: ${{ env.CACHE_CONFIG }},prefix=buildx/hub-ui/${{ matrix.arch }}/,mode=max

  finalize:
    needs: build
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Merge image tags
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          images: ${{ env.DOCKERHUB_REPO }}:latest-amd64,${{ env.DOCKERHUB_REPO }}:latest-arm64
          push: true

      - name: Setup variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "::set-output name=environment::prod"
          else
            echo "::set-output name=environment::stage"
          fi

      - name: Invoke workflow in hub-kubes repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
          workflow: release.yml
          repo: holaplex/hub-kubes
          inputs: '{ "service": "${{ env.SERVICE_NAME }}", "environment": "${{ steps.vars.outputs.environment }}", "commit_hash": "${{ github.sha }}"}'
